### ISSUE TITLE
about tokenize function

### ISSUE THREAD

**Issue by yc1999** [congxin95/PA-CRF#2]
Hi, thanks for ur code!
Since the dataset `FewEvent` is an English dataset,I think the tokenize function should be `BertEncoder.tokenize_en()` rather that `BertEncoder.tokenize()`:
https://github.com/congxin95/PA-CRF/blob/ab6a7c36f91349cdfd5df4042f9a8eb06679cec0/main.py#L143
https://github.com/congxin95/PA-CRF/blob/ab6a7c36f91349cdfd5df4042f9a8eb06679cec0/main.py#L149
https://github.com/congxin95/PA-CRF/blob/ab6a7c36f91349cdfd5df4042f9a8eb06679cec0/main.py#L155

**Comment by congxin95** [comment]
Thank you for pointing out my mistake. I have replaced the tokenize function. I re-ran the experiment in 5-way-5-shot setting and got 63.79% F1 of the test set. New codes have been updated. Thanks again.
